/**
 * Interface copy, per language.
 *
 * The English site is the Norwegian site with the language changed — same
 * components, same layout, same routes. That only works if the strings live
 * outside the components, so this is where the chrome's words go: the consent
 * banner, the navigation, the footer, the chat widget. Anything a visitor sees
 * on every page.
 *
 * **Not page body copy.** An article or a landing page is prose, not a bag of
 * labels, and forcing it through a key-value table produces the stilted
 * sentence-by-sentence translation that makes a site read as machine-made.
 * Those are translated as whole documents — the FAQ has `faq.en.ts`, and blog
 * posts have their own twin files.
 *
 * Keys are dotted and named for MEANING, not for the Norwegian words, so a
 * rewrite of the Norwegian does not orphan the key.
 */
import type { Locale } from "./i18n";

type Copy = Record<string, string>;

const nb: Copy = {
  // Consent — the first thing every visitor sees, and it was Norwegian on the
  // English site because it predates the translation entirely.
  // The region label is deliberately NOT the heading: a screen reader announces
  // the landmark before the heading, so "Consent to cookies" tells the listener
  // what the region is FOR, while the heading states what we do. Collapsing the
  // two lost that distinction and broke the test that pins it.
  "consent.regionLabel": "Samtykke til informasjonskapsler",
  "consent.title": "Vi bruker informasjonskapsler",
  "consent.body":
    "Nødvendige cookies gjør at nettsiden fungerer. Med ditt samtykke bruker vi i tillegg statistikk‑ og markedsføringscookies fra Google og Meta, slik at vi kan måle hvilke annonser som faktisk fører til en henvendelse. Du kan når som helst ombestemme deg.",
  "consent.readMoreIn": "Les mer i vår",
  "consent.cookiePolicy": "cookie-policy",
  "consent.privacyPolicy": "personvernerklæring",
  "consent.and": "og",
  "consent.acceptAll": "Godta alle",
  "consent.necessaryOnly": "Kun nødvendige",
  "consent.settings": "Innstillinger",
  "consent.readMore": "Les mer om cookies",
  "consent.analytics": "Analyse",
  "consent.analyticsHelp": "Hjelper oss å forstå hvordan siden brukes.",
  "consent.necessary": "Nødvendige",
  "consent.necessaryHelp": "Kreves for at nettsiden skal fungere. Kan ikke slås av.",
  "consent.save": "Lagre valg",

  // Chrome
  "nav.openPlatform": "Åpne plattformen",
  "nav.bookDemo": "Book demo",
  "nav.findVenues": "Finn ledige lokaler",
  "nav.talkToUs": "Snakk med oss",
  "nav.main": "Hovednavigasjon",
  "nav.skipToContent": "Hopp til hovedinnhold",
  "nav.tagline": "Enkel booking",
  "nav.toggleTheme": "Bytt tema",
  "nav.talkToUsMeanwhile": "Snakk med oss imens",
  "nav.home": "Hjem",
  "ui.close": "Lukk",
  "ui.back": "Tilbake",
  "nav.breadcrumbs": "Brødsmuler",

  // Homepage hero. The rotating word is a list, so it is joined with "|" and
  // split on read — a dictionary of strings stays a dictionary of strings.
  "hero.eyebrow": "Bookingplattform · 2026 · Norge",
  "hero.words":
    "Lokaler|Selskapslokaler|Møterom|Idrettshaller|Kulturhus|Bryllupslokaler|Julebordlokaler|Grendehus",
  "hero.headlineTail": "du trenger,",
  "hero.headlineEm": "og plattformen bak dem",
  "hero.lede":
    "Finn og book lokaler med ekte priser og ledige datoer, og betal trygt med Vipps. Er du utleier eller kommune, drifter du alt fra kalender til oppgjør i samme plattform.",
  "hero.bullet1": "Ekte priser og ledige datoer i sanntid",
  "hero.bullet2": "Betal trygt med Vipps eller faktura",
  "hero.bullet3": "Bygd for norske krav – BankID, GDPR og universell utforming",

  // How it works
  "how.label": "FUNKSJONALITET",
  "how.intro": "Fra forespørsel til oppgjør: én sammenhengende prosess.",
  "how.headline": "Booking med",
  "how.headlineEm": "få steg.",
  "how.step1.title": "Søknad",
  "how.step1.body":
    "Innbygger, lag, forening eller bedrift sender forespørsel via Digilist. Tilgjengelighet vises i sanntid; forespørsler innenfor regler bookes umiddelbart.",
  "how.step2.title": "Godkjenning",
  "how.step2.body":
    "Forespørsler utenfor regelverket går til administrator. Godkjenning kan delegeres til driftsroller, og automatregler dekker repeterende mønstre som sesongleie.",
  "how.step3.title": "Bekreftelse",
  "how.step3.body":
    "Automatisk bekreftelse med detaljer og betaling via Vipps eller kort. Driftsroller (vaktmester, renhold, vekter) varsles automatisk.",
  "how.step4.title": "Oppfølging",
  "how.step4.body":
    "Faktura og bilag til Visma, Tripletex, Fiken, PowerOffice, DNB Regnskap eller EHF/Peppol. Rapportering, KPI-er og økonomisk avstemming i én plattform.",

  "cta.label": "BOOK EN DEMO",

  // Marketplace tiles. The images and links are identical in both languages —
  // only the words change, which is the whole point of the mirror.
  "market.label": "FINN OG BOOK",
  "market.intro":
    "Lokaler, overnatting, arrangementer, utstyr og tjenester, samlet på ett sted. Ekte priser, ledige tider og betaling med Vipps.",
  "market.headline": "Alt du kan finne og",
  "market.headlineEm": "booke",
  "market.tile.venues": "Lokaler",
  "market.tile.venues.tag": "Selskap · møte · kultur",
  "market.tile.stays": "Overnatting",
  "market.tile.stays.tag": "Hytte · leilighet · feriehus",
  "market.tile.sport": "Sport og aktivitet",
  "market.tile.sport.tag": "Idrettshall · padel · svømming",
  "market.tile.events": "Arrangementer",
  "market.tile.events.tag": "Konsert · teater · sport",
  "market.tile.equipment": "Utstyr",
  "market.tile.equipment.tag": "Fest · verktøy · friluft",
  "market.tile.services": "Tjenester",
  "market.tile.services.tag": "Catering · DJ · dekor",

  "faq.label": "OFTE STILTE SPØRSMÅL",
  "faq.intro":
    "Det folk lurer mest på om Digilist: booking, betaling, sesongleie og samsvar. Finner du ikke svaret?",
  "faq.headline": "Ofte stilte",
  "faq.headlineEm": "spørsmål",
  "faq.seeAll": "Se alle spørsmål",

  "sync.label": "KANALER · TOVEIS SYNK",
  "sync.headline": "Én kalender.",
  "sync.headlineEm": "alle kanaler",
  "sync.lede":
    "Har du lokaler på Airbnb, Booking.com, Bookup eller Eventum? Koble dem til Digilist én gang – så holdes kalender og tilgjengelighet i sync automatisk. Ingen dobbeltarbeid, ingen dobbeltbookinger, alltid oppdatert overalt.",
  "sync.benefit1": "Synk kalender, priser og tilgjengelighet automatisk",
  "sync.benefit2": "Legg til nye oppføringer uten dobbeltarbeid",
  "sync.benefit3": "Alltid oppdatert – aldri dobbeltbookinger",
  "sync.benefit4": "Én admin for alle kanaler",
  "sync.cta": "Se hvordan synk fungerer",

  "agents.label": "INNEBYGD INTELLIGENS",
  "agents.intro":
    "Under overflaten jobber en flåte av AI-agenter som godkjenner, svarer, forklarer og varsler, så administrasjonen slipper.",
  "agents.headline": "Agenter og",
  "agents.headlineEm": "automatisering",
  "agents.a1.title": "Godkjenning & compliance",
  "agents.a1.body":
    "Hver oppføring gjennomgås mot GDPR, NSM, SOC 2 og universell utforming, i både tekst og bilder, før den publiseres. Rent innhold godkjennes, resten stoppes med konkret veiledning.",
  "agents.a2.title": "Svar på henvendelser",
  "agents.a2.body":
    "Kundeforespørsler får et varmt, korrekt førstesvar med én gang, og leser formål, dato og antall. Klager, pris og juss løftes alltid til en saksbehandler.",
  "agents.a3.title": "Sesongtildeling",
  "agents.a3.body":
    "Gjennomgår og forklarer sesongtildeling av halltid. Fanger klubber som faller utenfor, vurderer om resultatet er forsvarlig, og gir hver klubb en begrunnelse. Aldri «systemet bestemte».",
  "agents.a4.title": "Dagens oversikt",
  "agents.a4.body":
    "Vaktmester, renhold, vakthold og brannvern får en rolig, personlig oversikt over dagen, med tidene i riktig rekkefølge og det som må følges opp. Aldri en tom melding.",
  "agents.a5.title": "Markedsinnsikt",
  "agents.a5.body":
    "Leser tilbud og etterspørsel på tvers av markedsplassen og finner hullene, der det mangler lokaler folk faktisk leter etter, som en kort, rangert mulighetsoversikt.",
  "agents.a6.title": "Lag utkast fra en lenke",
  "agents.a6.body":
    "Har du lokalet på Airbnb, Booking.com, Finn eller Eventum, eller i et Word-dokument? Lim inn lenken eller last opp filen, så analyserer agenten innholdet og lager et ferdig utkast til oppføring du bare finpusser.",

  "b2b.label": "FOR UTLEIERE OG KOMMUNER",
  "b2b.intro":
    "Digilist drifter privat utleie og kommunal booking i samme løsning: privatbookinger, sesongleie til lag og foreninger, sambruk mellom avdelinger og innbyggerdialog med ID-porten.",
  "b2b.headline": "Fra ett lokale til",
  "b2b.headlineEm": "hele kommunen",
  "b2b.b1.title": "Alt samlet",
  "b2b.b1.body":
    "Bestilling, kalender, priser, vilkår og administrasjon i én plattform. Slutt med Excel, e-poster og dobbeltbookinger.",
  "b2b.b2.title": "Enkel å bruke",
  "b2b.b2.body":
    "Innbyggere og leietakere finner ledig tid, sender forespørsel og betaler uten opplæring. Universelt utformet, WCAG 2.0 AA.",
  "b2b.b3.title": "Effektiv drift",
  "b2b.b3.body":
    "Automatiserte regler, godkjenninger og oversikt reduserer manuelt arbeid. Driftsroller varsles automatisk ved bookinger.",
  "b2b.b4.title": "Skalerbar",
  "b2b.b4.body":
    "Fra ett selskapslokale til en kommune med tolv anlegg: sesongleie, lag og foreninger, tilskudd og fakturering.",

  // Demo form. The largest single block of copy on the homepage.
  "demo.heading": "Book en demo",
  "demo.lede":
    "Vi pakker ikke inn en standarddemo. Fortell oss kort hva dere driver med, så viser vi delene som faktisk angår dere.",
  "demo.badge1": "Ingen forpliktelser",
  "demo.badge2": "Rask respons",
  "demo.badge3": "Personlig gjennomgang",
  "demo.formHeading": "Send oss noen detaljer.",
  "demo.name": "Navn",
  "demo.namePlaceholder": "Ola Nordmann",
  "demo.email": "E-post",
  "demo.emailPlaceholder": "ola@kommune.no",
  "demo.org": "Organisasjon",
  "demo.orgPlaceholder": "Skien kommune",
  "demo.phone": "Telefon (valgfritt)",
  "demo.role": "Hvilken type virksomhet?",
  "demo.message": "Hva er viktig for dere? (valgfritt)",
  "demo.messagePlaceholder":
    "Sesongleie, ID-porten, EHF, antall anlegg, krav fra anskaffelse …",
  "demo.submit": "Send forespørsel",
  "demo.submitting": "Sender …",
  "demo.thanks": "Takk, vi tar kontakt.",
  "demo.sentTo": "Forespørselen er sendt til",
  "demo.replyTime": "svarer innen 24 timer på hverdager, som regel raskere.",
  "demo.error":
    "Vi fikk ikke sendt forespørselen. Prøv igjen, eller send e-post direkte til kontakt@digilist.no.",
  "demo.role.kommune": "Kommune",
  "demo.role.selskapslokale": "Selskapslokale / utleier",
  "demo.role.idrett": "Idrettsanlegg",
  "demo.role.kulturhus": "Kulturhus / scene",
  "demo.role.kontor": "Kontor / coworking",
  "demo.role.annet": "Annet",
  "demo.get1": "30–45 minutters demo, tilpasset ditt bruksområde",
  "demo.get2": "Gjennomgang av booking, betaling, sesongleie og fakturering",
  "demo.get3": "Spørsmål og svar: vi pakker ikke inn standarddemoen vår",
  "demo.get4": "Et notat med konkrete neste steg dersom dere vurderer pilot",
  "demo.need1": "Type virksomhet og typisk bookingvolum",
  "demo.need2": "Eventuelle krav fra anskaffelser eller intern compliance",
  "demo.need3": "Hvilke roller som skal se demoen (administrasjon, drift, økonomi)",

  "hero.trust1": "Book på 90 sekunder",
  "hero.trust1.sub": "Enkelt og raskt",
  "hero.trust2": "Universelt utformet",
  "hero.trust2.sub": "WCAG 2.1 AA",
  "hero.trust3": "BankID & Vipps",
  "hero.trust3.sub": "Trygg betaling",
  "hero.trust4": "Ledige datoer i sanntid",
  "hero.trust4.sub": "Ekte priser",

  "lane.renter.eyebrow": "For deg som skal leie",
  "lane.renter.heading": "Finn og book lokale, der du bor",
  "lane.renter.body":
    "Grendehus, kulturhus og selskapslokaler samlet, med ekte pris, ledig dato og betaling med Vipps. Book direkte, uten ringerunder eller ventetid på svar, med alt samlet på ett sted.",
  "lane.owner.eyebrow": "For utleier & kommune",
  "lane.owner.heading": "Plattformen som drifter utleien",
  "lane.owner.body":
    "Booking, sesongtildeling og innbyggerdialog i én plattform, med innebygd etterlevelse (GDPR, universell utforming, NSM). Ett system som erstatter regneark, e-post og løse betalingsløsninger, slik at dere beholder full oversikt og kontroll. Innbyggere, lag og foreninger booker selv, hele døgnet, uten telefonkø og uten dobbeltbookinger.",
  "lane.chooser": "Velg det som passer deg – så viser vi veien.",
  "agents.cta": "Se hvordan agentene jobber →",
  "pilot.label": "GRATIS PILOT FOR NORSKE KOMMUNER",
  "pilot.cta": "Se løsning for kommuner",
  "stories.intro":
    "Hverdagshistorier fra norske utleiere. Bookinger, automatisering og regnskap, sammenhengende.",
  "stories.footnote":
    "Flere referanser tilgjengelig på forespørsel. Kontakt salg for kunde- og nøkkeltallreferanser.",
  "stories.caption": "To av flere: referanser på forespørsel",
  "blogPreview.intro":
    "Tre artikler om kommunal booking, sesongleie og samsvar, skrevet for saksbehandlere, kulturkonsulenter og digitaliseringsansvarlige.",

  // Chatbot interface. The ANSWERS already follow the visitor's language
  // (lib/chatbot/language.ts); this is the furniture around them, which was
  // still Norwegian for an English visitor.
  "chat.assistant": "Digilist-assistenten",
  "chat.show": "Vis Digilist-assistenten",
  "chat.close": "Lukk Digilist-assistenten",
  "chat.closeConversation": "Lukk samtale",
  "chat.suggestions": "Forslag til neste spørsmål",
  "chat.suggestionsLabel": "Digilist-assistenten, forslag",
  "chat.closeSuggestions": "Lukk forslag",
  "chat.yourMessage": "Din melding",
  "chat.needHelp": "Hva trenger du hjelp med?",
  "chat.details": "Detaljer om behov, tidslinje eller spørsmål…",
  "chat.org": "Organisasjon eller kommune",
  "chat.orgExample": "F.eks. Rønningen Selskapslokale",

  "pricing.title": "Priser: abonnement uten transaksjonsgebyr | Digilist",
  "pricing.description":
    "Digilist tar ingen andel av bookinginntektene dine. Abonnement etter antall anlegg og behov, tilpasset pris for små og private aktører, og 6 måneder gratis for de 100 første kundene.",
  "pricing.label": "PRISER",
  "pricing.h1": "Vi tar ingen andel av det",
  "pricing.h1em": "du leier ut for",
  "pricing.lede":
    "Digilist er et abonnement, ikke en provisjon. Du betaler for å bruke plattformen og administrasjonspanelet — ingen transaksjonsavgift, ingen kostnad per booking, og ingen skjulte gebyrer. Leier du ut salen for 6 000 kroner, er de 6 000 kronene dine.",
  "pricing.cta": "Få pris for ditt oppsett",
  "pricing.faqCta": "Se hele FAQ-en",
  "pricing.visual": "ABONNEMENT · INGEN PROVISJON",
  "pricing.howHeading": "Slik fungerer prisen.",
  "pricing.whyHeading": "Hvorfor vi ikke har en prisliste",
  "pricing.whyBody":
    "Spennet mellom et grendehus med én sal og en fylkeskommune med tjueto skoler er så stort at ett tall enten blir for høyt for den ene eller meningsløst for den andre. Vi har heller valgt å publisere alt som avgjør prisen, og gi et konkret tilbud etter en kort samtale. Fortell oss hvor mange lokaler det gjelder, hva de brukes til, og omtrent hvor mange utleier det blir i året — så har du et tall.",
  "pricing.faqHeading": "Vanlige spørsmål om pris.",
  "pricing.offerHeading": "De 100 første kundene får 6 måneder gratis.",
  "pricing.offerBody":
    "Ingen binding i prøveperioden. Et bookingsystem er umulig å vurdere ordentlig på en demo — du finner det ut i mai, når tre lag vil ha samme hall.",
  "pricing.start": "Kom i gang",

  "faqPage.title": "FAQ · Digilist | Vanlige spørsmål om booking og samsvar",
  "faqPage.description":
    "Svar på de vanligste spørsmålene om Digilist, bookingsystem for kommuner og utleiere. SSA-L 2026, GDPR, ISO 27001, Vipps, BankID, sesongleie og mer.",
  "faqPage.h1": "Vanlige",
  "faqPage.h1em": "spørsmål",
  "faqPage.lede":
    "Alt du trenger å vite om Digilist: fra SSA-L 2026 og GDPR til sesongleie, betaling og integrasjoner.",
  "faqPage.categories": "Kategorier",
  "faqPage.stillQuestions": "FORTSATT SPØRSMÅL?",
  "faqPage.talkHeading": "Snakk med oss direkte.",
  "faqPage.talkBody":
    "Vi svarer raskt på e-post, eller booker en gratis 30 minutters demo der vi viser plattformen i ditt bruksområde.",
  "faqPage.talkCta": "Snakk med oss",

  // Footer — the same 14 markers on every page.
  "footer.funksjonalitet": "Funksjonalitet",
  "footer.brukerhistorier": "Brukerhistorier",
  "footer.kontakt": "Kontakt",
  "footer.lokaler": "Lokaler",
  "footer.lokaler_til_leie": "Lokaler til leie",
  "footer.overnatting": "Overnatting",
  "footer.arrangementer": "Arrangementer",
  "footer.utstyr": "Utstyr",
  "footer.tjenester": "Tjenester",
  "footer.booking_av_lokaler_og_m_terom": "Booking av lokaler og møterom",
  "footer.bookingsystem_for_utleie": "Bookingsystem for utleie",
  "footer.bookingsystem_for_kommuner": "Bookingsystem for kommuner",
  "footer.billettsystem": "Billettsystem",
  "footer.teknologi": "Teknologi",
  "footer.sikkerhet": "Sikkerhet",
  "footer.priser": "Priser",
  "footer.om_oss": "Om oss",
  "footer.blogg": "Blogg",
  "footer.faq": "FAQ",
  "footer.transparens": "Transparens",
  "footer.utleiemarkedet_2026": "Utleiemarkedet 2026",
  "footer.personvern": "Personvern",
  "footer.salgsvilk_r": "Salgsvilkår",
  "footer.cookies": "Cookies",
  "footer.tilgjengelighet": "Tilgjengelighet",

  "search.placeholder": "Søk i Digilist…",
  "search.label": "Søk i Digilist",
  "search.shortcuts": "Snarveier",
  "search.popular": "Populære søk",
  "search.blog": "Blogg",

  "stories.a.headline": "Fra excelark til kalenderautomatikk.",
  "stories.a.dek": "Privat selskapslokale i Asker som leier ut til selskaper, bryllup og jubileer.",
  "stories.a.body": "Som eier av et selskapslokale ønsket Rønningen å slutte å holde styr på bookinger i regneark. Med Digilist får gjestene en lenke der de selv ser ledige helger, betaler depositum og signerer leieavtalen digitalt.",
  "stories.a.quote": "Vi har eliminert dobbeltbookinger og fått automatisk faktura. Hver booking går fra forespørsel til betalt på under fem minutter.",
  "stories.a.byline": "Eier",
  "stories.b.headline": "Én plattform for haller, møterom og kantiner.",
  "stories.b.dek": "Kommunal kulturetat med tolv anlegg, ca. 340 lag og foreninger og 1 200 bookinger i måneden.",
  "footer.tagline": "Én plattform for norske lokaler. Finn og book som privatperson, drift og forvalt som kommune eller utleier.",
  "footer.colophon": "TRYKKET DIGITALT · OSLO · SATT MED NEWSREADER OG INTER",
  "demo.chatLine": "og få svar i chat på under et minutt i kontortid.",
  "home.title": "Digilist · Én plattform for alt som leies ut",
  "home.description": "Digital bookingplattform for selskapslokaler, idrettshaller, møterom og kulturhus. Sanntidskalender, Vipps, BankID, EHF, sesongleie. ISO 27001-sertifisert.",
  "stories.a.customer": "KUNDE",
  "stories.b.body": "Kulturkonsulenten håndterer sesongleie til lag og foreninger, privatbookinger og sambruk mellom kantiner og møterom. Driftsroller (vaktmestere, renhold, vektere) varsles automatisk ved bookingbekreftelse. Tilskudd til lag og foreninger fordeles via sesongleie-modulen.",
  "stories.b.quote": "Vi har samlet tolv anlegg, hundrevis av foreninger og kommunal fakturering i én plattform, og innbyggerne booker via ID-porten.",
  "stories.b.byline": "KULTURKONSULENT · NORDRE FOLLO KOMMUNE",
  "stories.b.stat1": "ANLEGG I DRIFT",
  "stories.b.stat2": "AKTIVE LAG/FORENINGER",
  "stories.b.stat3": "BOOKINGER / MÅNED",
  "stories.reference": "BE OM REFERANSE",
  "market.find": "FINN",
  "footer.ctaHeading": "Klar for å se Digilist i praksis?",
  "footer.productOf": "Et produkt av",
  "blog.back": "Tilbake til blogg",
  "blog.readArticle": "Les artikkel",
  "demo.whatYouGet": "HVA DU FÅR",
  "demo.whatWeNeed": "HVA VI TRENGER FRA DEG",
  "demo.informalChat": "Foretrekker du en uformell prat først?",
  "demo.weFollow": "Vi følger",
  "demo.privacyPolicy": "personvernerklæringen",
  "stories.a.body2": "Som eier av et selskapslokale ønsket Rønningen å slutte å holde styr på bookinger i regneark. Med Digilist får gjestene en lenke der de selv ser ledige helger, betaler depositum og signerer leieavtalen digitalt.",
  "blog.crumbVenues": "Booking av lokaler og møterom",
  "blog.crumbHalls": "Idrettshaller og gymsaler",
  "blog.crumbMunicipal": "Bookingsystem for kommuner",
  "blog.crumbMeeting": "Møterom",
  "blog.crumbFunction": "Selskapslokaler",
  "blog.crumbCulture": "Kulturhus og kantiner",
  "useCase.crumbRoot": "Bruksområder",
  "useCase.breadcrumbs": "Brødsmuler",
  "useCase.challenges": "Hva utfordringene er i dag",
  "useCase.whatWeDo": "Hva Digilist gjør med det",
  "useCase.whoUses": "Hvem bruker dette",
  "about.title": "Om Digilist: norsk bookingplattform | Digilist",
  "about.description": "Digilist er utviklet av Xala Technologies AS, et norsk teknologiselskap på Nesbru. Vi bygger én plattform for utleie og kommunal booking, med samsvar og norsk datalagring.",
  "demo.choose": "Velg …",
  "homePricing.whyNoList": "Vi publiserer ingen prisliste: spennet mellom et grendehus med én sal og en fylkeskommune med tjueto skoler gjør ett tall feil for nesten alle. Vi publiserer i stedet alt som avgjør prisen.",
  "homePricing.rule": "PRISER · KAMPANJE",
  "homePricing.h2": "Abonnement,",
  "homePricing.h2em": "ikke provisjon",
  "homePricing.lede": "Vi tar ingen andel av det du tar betalt. Du betaler for å bruke Digilist og administrasjonspanelet — ikke per booking, ikke en prosent av leien, og ingen skjulte gebyrer. Går du fra tjue utleier i året til seksti, koster ikke Digilist mer.",
  "homePricing.privateLabel": "PRIVATE UTLEIERE",
  "homePricing.privateTitle": "Ett lokale eller femti",
  "homePricing.privateBody": "Selskapslokaler, grendehus, gårder, klubber og foreninger. Nivået følger antall lokaler og hvor mange som bruker systemet — ikke hvor mye du tjener. Å gå fra ett lokale til fem endrer abonnementet; flere bookinger i samme lokale gjør det ikke. Små og private aktører får egne, tilpassede priser.",
  "homePricing.publicLabel": "KOMMUNER",
  "homePricing.publicTitle": "Anlegg, ikke bookinger",
  "homePricing.publicBody": "Prisen avhenger av antall anlegg, brukermengde og integrasjoner mot økonomi- og fagsystemer. Sesongleie, ID-porten, EHF-fakturering og SSA-L 2026 er en del av plattformen, ikke tillegg. Ingen andel av det innbyggere, lag og foreninger betaler.",
  "homePricing.offerEyebrow": "KAMPANJE",
  "homePricing.offerTitle": "6 måneder gratis for de 100 første kundene",
  "homePricing.offerBody": "Vi hjelper med oppsett og publisering i prøveperioden, og du får egen administrativ tilgang for videre drift. Ingen binding underveis — etterpå velger du nivå ut fra behovet.",
  "homePricing.ctaPrices": "Se hva som avgjør prisen",
  "homePricing.ctaDemo": "Be om pristilbud",
  "homePricing.noFee": "Ingen transaksjonsavgift",
  "homePricing.noHidden": "Ingen skjulte gebyrer",
  "homePricing.included": "Integrasjonene er inkludert",
  "a11y.homeLink": "Digilist, gå til forsiden",
  "a11y.heroVideo": "Digilist i praksis – fra søk til booking",
  "chat.searchPlaceholder": "Søk eller spør om Digilist …",
  "demo.orgOrCouncil": "Organisasjon eller kommune",
  "useCase.howItWorks": "SLIK FUNGERER DET",
  "useCase.seeHow": "SE HVORDAN DET FUNGERER",
  "status.card.report": "Per-overflate scoringer for SEO, tilgjengelighet, sikkerhet og lenker, samme data vårt interne team ser.",
  "status.card.meeting": "30–45 min, NDA, sammendrag av siste pen-test, vulnerability-status og beredskapsplan.",
  "status.card.securityTxt": "Fant du en sårbarhet? Vi tar imot ansvarlig rapportering på sikkerhet@digilist.no. Kvittert innen 24 timer.",
  "tr.card.meeting": "30–45 minutter, NDA, sammendrag av siste pen-test, vulnerability-status, RPO/RTO og beredskapsplan.",
  "tr.card.securityTxt": "Fant du en sårbarhet? Vi tar imot ansvarlig sårbarhetsrapportering på sikkerhet@digilist.no. Rapportering kvittert innen 24 timer.",
  "tr.areasIntro": "Rapporten dekker fem områder.",
  "tr.areaSeo": "SEO",
  "tr.areaSeoBody": "måler hvor synlig plattformen er i søk: titler, metadata, canonical og strukturert data.",
  "tr.areaA11y": "Tilgjengelighet",
  "tr.areaA11yBody": "sjekker WCAG-samsvar: overskriftshierarki, alt-tekster, landemerker og tastaturnavigasjon for skjermlesere.",
  "tr.areaSec": "Sikkerhet",
  "tr.areaSecBody": "vurderer HTTP-sikkerhetsheadere, TLS-sertifikater og at ingen sensitive filer er eksponert.",
  "tr.areaUptime": "Oppetid",
  "tr.areaUptimeBody": "følger tilgjengelighet og responstid per tjeneste, med varsling ved avvik.",
  "tr.areaLinks": "Lenker",
  "tr.areaLinksBody": "verifiserer at ingen utgående lenker er brutt. Hver overflate i økosystemet (markedssiden, booking-appen, dashbordet, dokumentasjonen og API-et) skannes uavhengig, og tallene nedenfor er hentet direkte fra siste kjøring, uten manuell redigering eller utvalg.",
  "tr.measuredUptime": "MÅLT OPPETID (30 DAGER)",
  "tr.avgScore": "Snittscore",
  "tr.warnings": "Advarsler",
  "tr.methodRule": "METODE",
  "tr.apiError": "API svarte med",
  "tr.apiErrorTail": ". Prøv å laste siden på nytt",
  "tr.unknownType": "ukjent type",
  "tr.fw.iso27001": "Annex A: Organisatoriske, personell-, fysiske og teknologiske kontroller.",
  "tr.fw.soc2": "Common Criteria: kontrollmiljø, risiko, tilgang og systemoperasjoner.",
  "tr.fw.gdpr": "Kjerneartikler: personvern, lovlig grunnlag, sletting og brudd-håndtering.",
  "tr.val.ssl": "Sertifikat, cipher suites, protokoll-styrke. Mål A eller A+.",
  "tr.val.headers": "HSTS, CSP, X-Frame-Options, Referrer-Policy. Bokstavkarakter.",
  "tr.val.observatory": "Helhetlig sikkerhetsposture mot moderne nettstandarder.",
  "tr.val.pagespeed": "Core Web Vitals: LCP, CLS, INP. Mobil + desktop.",
  "tr.comp.iso27001": "Informasjonssikkerhetsstyring",
  "tr.comp.iso27701": "Personverninformasjonsstyring",
  "tr.comp.gdpr": "EU/EØS-datalokasjon",
  "tr.label.security": "Sikkerhet",
  "tr.col.uptime": "Oppetid",
  "tr.col.security": "Sikkerhet",
  "tr.col.a11y": "Tilgjengelighet",
  "tr.col.seo": "SEO",
  "tr.col.links": "Lenker",
  "tr.m.uptime": "Oppetid & SSL.",
  "tr.m.uptimeBody": "HTTP-status, responstid og sertifikat-utløp via",
  "tr.m.seo": "SEO.",
  "tr.m.seoBody": "Titler, descriptions, canonical, OG/Twitter, JSON-LD, alt-text, duplikat-metadata, ødelagte interne lenker.",
  "tr.m.a11y": "Tilgjengelighet.",
  "tr.m.a11yBody": "Lang-attributt, alt-tekst, label-for, heading-hierarki, ARIA-landmark, knapp- og lenkenavn (cheerio-baseline; axe-core kommer).",
  "tr.m.sec": "Sikkerhet.",
  "tr.m.secBody": "HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, sensitive-fil-prober, mixed content, source maps.",
  "tr.m.links": "Lenker.",
  "tr.m.linksBody": "Eksterne lenker HEAD-sjekket, 405→GET fallback, dedup-ert per URL.",
  "tr.metaTitle": "Transparens · kvalitetsrapport for Digilist",
  "tr.metaDescription": "Live kvalitetsrapport: SEO, tilgjengelighet, sikkerhet, oppetid og lenker, automatisk skannet på tvers av Digilist-økosystemet.",
  "tr.h1": "Transparens.",
  "tr.lede1a": "En kommunal CIO bør vite hva slags plattform de velger. Denne siden viser",
  "tr.ledeEm": "Digilist sin egen",
  "tr.lede1b": "kvalitet: SEO, tilgjengelighet, sikkerhet, oppetid og lenker, automatisk skannet og oppdatert.",
  "tr.lede2": "Skanninger kjøres minst hver 15. minutt for oppetid og daglig for hele økosystemet. Det vi viser her er det samme som vårt interne team ser.",
  "tr.loading": "Henter live data…",
  "tr.errorPrefix": "Beklager, kommer tilbake snart.",
  "tr.surfacesActive": "Overflater aktive",
  "tr.criticalFindings": "Kritiske funn",
  "tr.noBlocking": "Ingen blokkerende",
  "tr.underRemediation": "Under aktiv utbedring",
  "tr.recommendedImprovement": "Anbefalt forbedring",
  "tr.complianceNote": "Tallene viser implementeringsgrad, andelen anvendelige kontroller med dokumentert tilstand «Implementert» (full kreditt) eller «Delvis» (halv). Detaljer over hver kontroll er tilgjengelig på forespørsel for kommunale kunder under NDA.",
  "tr.noSurfaces": "Ingen aktive produksjons-overflater i siste skanning.",
  "tr.whatWeMeasure": "Hva vi måler",
  "tr.scoreReading": "Score-tolkning",
  "tr.band95": "utmerket",
  "tr.band85": "bra",
  "tr.band70": "akseptabelt",
  "tr.validatorRule": "UAVHENGIG VURDERING",
  "tr.validatorH2": "Verifiser oss hos uavhengige tredjeparter",
  "tr.validatorLede": "Vi kjører våre egne automatiske skanninger (oversikten over), men du bør ikke ta vårt ord for det. Sjekk digilist.no selv hos disse uavhengige sikkerhets- og kvalitetsmålerne. De gir sanntidsdom.",
  "tr.liveReport": "Se live rapport",
  "tr.liveNote": "Live oppslag. Klikk en boks for å kjøre skanning hos tredjepart i sanntid.",
  "tr.complianceRule": "SAMSVAR",
  "tr.nextRule": "VEIEN VIDERE",
  "tr.nextH2": "Vil du se mer?",
  "tr.nextLede": "Vi deler gjerne sammendrag av siste penetrasjonstest og sårbarhetsstatus under NDA. Be om et møte. Vi viser rapportene side-om-side med plattformen.",
  "tr.readAudit": "Les om sikkerhetsrevisjon",
  "tr.score.excellent": "Utmerket",
  "tr.score.good": "Bra",
  "tr.score.acceptable": "Akseptabelt",
  "tr.score.needsWork": "Trenger forbedring",
  "tr.score.critical": "Kritisk",
  "tr.score.noData": "Ingen data",
  "tr.label.uptime": "SSL & responstid",
  "tr.label.a11y": "Tilgjengelighet",
  "status.metaTitle": "Driftsstatus · Digilist",
  "status.metaDescription": "Sanntidsstatus for Digilist-økosystemet: oppetid, SLA, sikkerhet og tilgjengelighet på tvers av digilist.no, app.digilist.no, dashboard.digilist.no og dokumentasjon.",
  "status.h1": "Status.",
  "status.lede1": "Sanntid for Digilist-økosystemet. Hver overflate skannes automatisk. Vi måler det",
  "status.ledeEm": "du",
  "status.lede2": "opplever, ikke bare serverpuls. Når noe ryker, ser du det her først.",
  "status.slaNote": "SLA-tall under er forpliktende. Avvik fra mål utløser hendelsesrapport publisert i loggen nederst.",
  "status.lastUpdated": "Sist oppdatert",
  "status.scanNote": "skanninger kjøres automatisk · siden viser siste tilgjengelige skanning",
  "status.loading": "Henter live data…",
  "status.unavailable": "Statusmålingene lastes ikke akkurat nå. Skanningene kjører videre i bakgrunnen.",
  "status.slaRule": "SLA-FORPLIKTELSER",
  "status.slaH2": "Forpliktet oppetid vs. faktisk.",
  "status.slaLede": "Vi forplikter oss til konkrete oppetidstall per overflate-type. Tallet",
  "status.slaNoData": "Ingen data",
  "status.slaMet": "SLA møtt",
  "status.slaBreach": "Under SLA",
  "status.surfacesRule": "OVERFLATER",
  "status.surfacesLede": "Per-overflate status (operativ, redusert eller nede) basert på siste",
  "status.incidentRule": "HENDELSESLOGG",
  "status.noIncidents": "Ingen hendelser registrert de siste 90 dagene.",
  "status.validatorRule": "UAVHENGIG VURDERING",
  "status.validatorH2": "Verifiser oss hos uavhengige tredjeparter",
  "status.validatorLede": "Tallene over kommer fra våre egne skanninger. Sjekk digilist.no",
  "status.liveReport": "Se live rapport",
  "status.nextRule": "VEIEN VIDERE",
  "status.nextH2": "Trenger du mer detalj?",
  "status.nextLede": "Full transparensrapport, sikkerhetsmøte under NDA og ansvarlig",
  "status.eco.operational": "Alle systemer operative",
  "status.eco.degraded": "Redusert ytelse på enkelte overflater",
  "status.eco.outage": "Pågående hendelse på minst én overflate",
  "status.dot.operational": "Operativ",
  "status.dot.degraded": "Redusert",
  "status.dot.down": "Nede",
  "status.type.marketing": "Markedsføring",
  "status.type.app": "App",
  "status.type.dashboard": "Dashbord",
  "status.type.docs": "Dokumentasjon",
  "status.type.api": "API",
  "status.type.status": "Status",
  "status.sla.marketing": "Offentlige sider: markedsføring, blogg, dokumentasjon",
  "status.sla.docs": "Dokumentasjon",
  "status.sla.status": "Status-side (denne)",
  "status.sla.app": "Innloggede applikasjons-overflater",
  "status.sla.dashboard": "Tenant-administrasjon",
  "status.sla.api": "Offentlige API-endepunkter",
  "tools.title": "Gratis verktøy for å leie lokale – pris og kapasitet | Digilist",
  "tools.description": "Gratis verktøy for deg som skal leie lokale: leiepriskalkulator og kapasitetskalkulator. Estimer pris og areal for bryllup, fest, møte eller konferanse – uten innlogging.",
  "tools.keywords": "verktøy leie lokale, leiepriskalkulator, kapasitetskalkulator, planlegge arrangement, budsjett lokale",
  "tools.crumb": "Verktøy",
  "tools.h1": "Gratis verktøy for å leie lokale",
  "tools.lede": "Enkle, ærlige verktøy for deg som planlegger et arrangement – estimer pris og areal før du leter etter lokale. Ingen innlogging, ingen forpliktelser.",
  "tools.open": "Åpne verktøyet",
  "tools.priceTitle": "Leiepriskalkulator",
  "tools.priceDesc": "Hva koster det å leie lokale? Få et ærlig, veiledende prisintervall justert for lokaltype, by, ukedag og sesong.",
  "tools.capTitle": "Kapasitetskalkulator",
  "tools.capDesc": "Hvor stort lokale trenger du? Regn ut anbefalt areal ut fra antall gjester og oppsett, og se hvilke lokaltyper som passer.",
  "calc.type.selskapslokale": "Selskapslokale / festlokale",
  "calc.type.grendehus": "Grendehus / foreningslokale",
  "calc.type.moterom": "Møterom",
  "calc.type.konferanselokale": "Konferanselokale",
  "calc.type.kulturhus": "Kulturhus / storsal",
  "calc.type.idrettshall": "Idrettshall",
  "calc.city.oslo": "Oslo",
  "calc.city.bergen": "Bergen",
  "calc.city.trondheim": "Trondheim",
  "calc.city.stavanger": "Stavanger",
  "calc.city.kristiansand": "Kristiansand",
  "calc.city.tromso": "Tromsø",
  "calc.city.drammen": "Drammen",
  "calc.city.baerum": "Bærum",
  "calc.city.annet": "Annet / mindre sted",
  "calc.unit.dag": "dag",
  "calc.unit.arrangement": "arrangement",
  "calc.unit.time": "time",
  "calc.factor.weekend": "Helg",
  "calc.factor.weekday": "Hverdag",
  "calc.factor.highSeason": "Høysesong mai–sep",
  "calc.factor.lowSeason": "Lavsesong",
  "price.title": "Leiepriskalkulator: hva koster det å leie lokale? | Digilist",
  "price.description": "Gratis leiepriskalkulator: få et ærlig, veiledende prisintervall for å leie selskapslokale, møterom, konferanselokale, kulturhus eller idrettshall – justert for by, sesong og ukedag. Ikke et tilbud, men en god pekepinn for budsjettet.",
  "price.keywords": "hva koster det å leie lokale, leiepris lokale, pris selskapslokale, priskalkulator lokale, leie lokale pris, leiepriskalkulator",
  "price.crumb": "Leiepriskalkulator",
  "price.howH2": "Slik beregner vi estimatet",
  "price.howP1a": "Estimatet tar utgangspunkt i typiske prisintervaller for hver lokaltype i det norske utleiemarkedet, og justerer dem med noen få, tydelige faktorer. Vi oppgir alltid et ",
  "price.howP1strong": "intervall",
  "price.howP1b": ", ikke en eksakt pris, fordi den reelle prisen avhenger av det konkrete lokalet.",
  "price.b1strong": "Lokaltype og størrelse",
  "price.b1": " betyr mest. Et grendehus koster en brøkdel av et sentralt selskapslokale.",
  "price.b2strong": "By og sted:",
  "price.b2": " sentrale strøk i Oslo og de større byene ligger høyere; mindre steder rimeligere.",
  "price.b3strong": "Ukedag:",
  "price.b3": " lørdager er mest ettertraktet og dyrest; hverdager er billigere og har bedre tilgjengelighet.",
  "price.b4strong": "Sesong:",
  "price.b4": " mai–september er høysesong for bryllup og fester.",
  "price.howP2a": "Husk at ",
  "price.howP2strong": "tilleggstjenester",
  "price.howP2b": " – rengjøring, bemanning, AV-utstyr, catering og depositum – ofte kommer i tillegg til grunnleien. På Digilist vises tilleggene som egne linjer, så du ser sluttsummen før du bekrefter.",
  "price.h1": "Hva koster det å leie et lokale?",
  "price.ledeA": "Få et ærlig, veiledende prisintervall for å leie lokale i Norge – justert for lokaltype, antall gjester, by, ukedag og sesong. Dette er ",
  "price.ledeStrong": "et estimat, ikke et tilbud",
  "price.ledeB": ": faktisk pris settes av utleier og ser du på det enkelte lokalet.",
  "price.venueType": "Lokaltype",
  "price.city": "By / sted",
  "price.weekend": "Helg (lør/søn)",
  "price.highSeason": "Høysesong (mai–september)",
  "price.estimated": "Estimert leiepris",
  "price.per": "per",
  "price.adjustedFor": "Justert for:",
  "price.disclaimer": "Et veiledende intervall – ikke et tilbud. Faktisk pris varierer med lokalet og tilleggstjenester.",
  "price.findAvailable": "Finn ledige",
  "price.realPrices": "Se ekte priser og ledige datoer på",
  "price.empty": "Velg lokaltype for et estimat.",
  "price.guestsWord": "gjester",
  "cap.ledeA": "Regn ut anbefalt areal ut fra antall gjester og oppsett, og se hvilke lokaltyper som passer. Tallene er ",
  "cap.ledeStrong": "standard planleggingstall",
  "cap.ledeB": " – en god pekepinn, ikke en fasit.",
  "cap.howP1b2": ", altså hvordan gjestene skal sitte eller stå. En sittende middag med runde bord krever mest plass; en stående mottakelse minst.",
  "cap.rowDinner": "Sittende middag (runde bord):",
  "cap.rowMingle": "Mingling / stående:",
  "cap.rowClass": "Klasserom / kurs:",
  "cap.rowTheatre": "Kino / teater (stolrader):",
  "cap.perGuest": "per gjest.",
  "cap.perPersonShort": "per person.",
  "cap.howP2a": "Legg til areal for ",
  "cap.howP2strong": "dansegulv, scene, buffé, bar, garderobe og rømningsveier",
  "cap.howP2b": " – typisk 15–25 % ekstra. Skal barn løpe rundt, eller har du et variert program, velg heller et lokale i øvre del av intervallet.",
  "cap.title": "Kapasitetskalkulator: hvor stort lokale trenger du? | Digilist",
  "cap.description": "Gratis kapasitetskalkulator: regn ut hvor stort lokale (m²) du trenger ut fra antall gjester og oppsett – sittende middag, mingling, klasserom eller kino. Med standard planleggingstall og forslag til lokaltyper som passer.",
  "cap.keywords": "hvor stort lokale, kapasitet lokale, m2 per gjest, hvor mange gjester lokale, kapasitetskalkulator, antall gjester lokale",
  "cap.crumb": "Kapasitetskalkulator",
  "cap.badge": "Gratis verktøy",
  "cap.h1": "Hvor stort lokale trenger du?",
  "cap.lede": "Regn ut anbefalt areal ut fra antall gjester og oppsett, og se hvilke lokaltyper som passer. Tallene er standard planleggingstall, ikke bindende.",
  "cap.guests": "Antall gjester",
  "cap.occasion": "Arrangementstype",
  "cap.layout": "Oppsett",
  "cap.perPerson": "m² per person",
  "cap.recommended": "Recommended area",
  "cap.for": "for",
  "cap.guestsWord": "gjester",
  "cap.basis": "Legg til 15–25 % for dansegulv, scene, buffé og garderobe. Standard planleggingstall – sjekk lokalets oppgitte kapasitet.",
  "cap.basedOn": "Basert på",
  "cap.typesFor": "Lokaltyper som passer",
  "cap.findVenues": "Finn ledige lokaler",
  "cap.empty": "Fyll inn antall gjester for et estimat.",
  "cap.howH2": "Slik regner du ut kapasitet",
  "cap.faqH2": "Ofte stilte spørsmål",
  "cap.explore": "Utforsk videre",
  "cap.venuesToRent": "Lokaler til leie",
  "cap.howP1a": "Arealbehovet styres først og fremst av",
  "cap.howP1strong": "oppsettet",
  "cap.howP1b": ", altså hvordan gjestene skal sitte eller stå. En sittende middag med runde bord krever mest plass; en stående mottakelse minst.",
  "cap.byline": "Digilist-redaksjonen",
  "cap.bylineRole": "Bookingsystem for utleie",
  "calc.oppsett.middag": "Sittende middag (runde bord)",
  "calc.oppsett.mingling": "Mingling / stående mottakelse",
  "calc.oppsett.klasserom": "Klasserom / kurs (bord + stoler)",
  "calc.oppsett.kino": "Kino / teater (stolrader)",
  "calc.arr.bryllup": "Bryllup",
  "calc.arr.konfirmasjon": "Konfirmasjon",
  "calc.arr.firmafest": "Firmafest / julebord",
  "calc.arr.mote": "Møte",
  "calc.arr.konferanse": "Konferanse",
  "calc.arr.mingling": "Mingling / mottakelse",
  "pilot.delivers.0": "Sanntids tilgjengelighetskalender",
  "pilot.delivers.1": "Enkel booking og forespørsler",
  "pilot.delivers.2": "Håndtering av sesongleie for lag og foreninger",
  "pilot.delivers.3": "Oversikt over lokaler og idrettsanlegg",
  "pilot.delivers.4": "Digital saksbehandlingsflyt",
  "pilot.delivers.5": "Administrativ godkjenning av forespørsler",
  "pilot.delivers.6": "Fakturagrunnlag og betalingsoversikt",
  "pilot.delivers.7": "Mobilvennlig og universelt utformet løsning",
  "pilot.delivers.8": "Enkel administrasjon og oppdatering av innhold",
  "pilot.delivers.9": "Bedre synlighet av kommunale tilbud og aktiviteter",
  "pilot.needs.0": "Lokaler eller anlegg kommunen administrerer",
  "pilot.needs.1": "Korte beskrivelser",
  "pilot.needs.2": "Bilder eller lenker, dersom tilgjengelig",
  "pilot.needs.3": "Kontaktinformasjon",
  "pilot.needs.4": "Eventuell informasjon om booking eller sesongleie",
  "pilot.rule": "PILOT FOR NORSKE KOMMUNER",
  "pilot.h2": "En invitasjon til",
  "pilot.h2em": "norske kommuner",
  "pilot.p1": "Digilist er en moderne og universelt utformet plattform for håndtering og synliggjøring av kommunale lokaler, idrettsanlegg, møterom og arrangementer.",
  "pilot.p2": "Vi inviterer kommunen til å delta i et pilotinitiativ der vi hjelper med å gjøre kommunale utleieobjekter og aktiviteter mer tilgjengelige, enklere å administrere og lettere å finne for innbyggere, lag, organisasjoner og arrangører.",
  "pilot.p3em": "Målet er ikke å erstatte eksisterende løsninger",
  "pilot.p3tail": "eller arbeidsprosesser, men å utforske hvordan Digilist kan fungere som et moderne supplement for innbyggere og administrasjon.",
  "pilot.p4": "Vi hjelper med oppsett og publisering uten kostnad i pilotfasen. Kommunen får egen administrativ tilgang for videre drift.",
  "pilot.requestCta": "Be om pilot",
  "pilot.role": "Xala Technologies AS",
  "pilot.date": "Oslo · 2026",
  "pilot.offerLabel": "TILBUDSPAKKE",
  "pilot.deliverEm": "leverer",
  "pilot.inputLabel": "INPUT FRA KOMMUNEN",
  "pilot.needH3": "Vi trenger",
  "pilot.needH3em": "fra kommunen",
  "pilot.footnote": "Pilotfasen er gratis. Kommunen forplikter seg ikke til videre bruk eller anskaffelse.",
  "tech.title": "Teknologi og sikkerhet: stack, arkitektur og samsvar | Digilist",
  "tech.description": "Teknologien bak Digilist: React 19, Convex reaktiv runtime, PostgreSQL 16 i Norge og EU, ISO 27001/27701, GDPR, WCAG 2.1 AA, ID-porten, EHF/Peppol og norske integrasjoner.",
  "tech.rule": "PLATTFORM · SIKKERHET · SAMSVAR",
  "tech.h1": "Teknologien",
  "tech.h1em": "under Digilist",
  "tech.lede": "En reaktiv runtime, norsk og europeisk datalagring, og samsvar bygget inn fra grunnen: ISO 27001/27701, GDPR og universell utforming. Her er stacken, arkitekturen og integrasjonene som driver plattformen.",
  "tech.faqRule": "OFTE STILTE SPØRSMÅL",
  "tech.faqH2": "Teknologi og",
  "tech.faqH2em": "samsvar",
  "tech.faqLede": "Stack, datalagring, sertifiseringer og oppetid: svar på det tekniske kjøpere og saksbehandlere spør om.",
  "tech.seeAll": "Se alle spørsmål",
  "tech.ctaHeading": "Vil du se det under panseret?",
  "tech.ctaBody": "Book en demo, så går vi gjennom arkitektur, datalagring, samsvarsdokumentasjon og integrasjonene som er relevante for ditt oppsett.",
  "bookDemo.title": "Book demo av Digilist · Norsk bookingplattform for kommuner",
  "bookDemo.description": "Be om en gratis 30–45 minutters demo av Digilist. Vi viser hvordan plattformen håndterer ditt bruksområde: kommune, selskapslokale, idrettsanlegg eller kulturhus.",
  "bookDemo.back": "Tilbake til forsiden",
  "bookDemo.rule": "IX. KONTAKT",
  "bookDemo.crumb": "Book demo",
  "about.label": "OM DIGILIST",
  "about.h1": "Én plattform for alt",
  "about.h1em": "som leies ut",
  "about.lede": "Digilist er utviklet av Xala Technologies AS, et norsk teknologiselskap på Nesbru. Vi bygger digitale løsninger for offentlig sektor og næringsliv, med samsvar, universell utforming og norsk datalagring som utgangspunkt.",
  "about.techCta": "Teknologi & sikkerhet",
  "about.ctaHeading": "Snakk med folkene bak plattformen.",
  "about.ctaBody": "Book en demo eller ta kontakt, så viser vi hvordan Digilist passer for din kommune eller virksomhet.",
  "chat.closeShort": "Lukk",
  "pilot.body": "Vi hjelper kommunen med oppsett og publisering uten kostnad i pilotfasen, og dere får egen administrativ tilgang for videre drift. Målet er å supplere eksisterende prosesser, ikke erstatte dem.",
  "footer.ctaBody": "Book en personlig demo, eller still spørsmål direkte i chat. Vi svarer på under et minutt i kontortid.",
  "blogPreview.seeAll": "Se alle artikler",
  "interest.finn": "Finn og book lokale",
  "interest.kalender": "Booking & kalender",
  "interest.betaling": "Betaling & oppgjør",
  "interest.kanaler": "Kanaler & synk",
  "interest.ai": "AI-agenter",
  "interest.kommune": "Bookingsystem for kommune",
  "interest.heading": "Hva er du mest interessert i?",
  "chat.s1": "Finn selskapslokale",
  "chat.s2": "Hva koster det å leie et lokale?",
  "chat.s3": "Bookingsystem for kommuner",
  "chat.s4": "Sesongtildeling",
  "chat.s5": "Book demo",
  "footer.i_navigasjon": "I · NAVIGASJON",
  "footer.ii_markedsplass": "II · MARKEDSPLASS",
  "footer.iii_l_sninger": "III · LØSNINGER",
  "footer.iv_selskap": "IV · SELSKAP",
  "footer.v_lokaler_til_leie": "V · LOKALER TIL LEIE",
};

const en: Copy = {
  "consent.regionLabel": "Consent to cookies",
  "consent.title": "We use cookies",
  "consent.body":
    "Necessary cookies make the site work. With your consent we also use statistics and marketing cookies from Google and Meta, so we can measure which ads actually lead to an enquiry. You can change your mind at any time.",
  "consent.readMoreIn": "Read more in our",
  "consent.cookiePolicy": "cookie policy",
  "consent.privacyPolicy": "privacy statement",
  "consent.and": "and",
  "consent.acceptAll": "Accept all",
  "consent.necessaryOnly": "Necessary only",
  "consent.settings": "Settings",
  "consent.readMore": "Read more about cookies",
  "consent.analytics": "Analytics",
  "consent.analyticsHelp": "Helps us understand how the site is used.",
  "consent.necessary": "Necessary",
  "consent.necessaryHelp": "Required for the site to work. Cannot be turned off.",
  "consent.save": "Save choices",

  "nav.openPlatform": "Open the platform",
  "nav.bookDemo": "Book a demo",
  "nav.findVenues": "Find available venues",
  "nav.talkToUs": "Talk to us",
  "nav.main": "Main navigation",
  "nav.skipToContent": "Skip to main content",
  "nav.tagline": "Booking made simple",
  "nav.toggleTheme": "Switch theme",
  "nav.talkToUsMeanwhile": "Talk to us meanwhile",
  "nav.home": "Home",
  "ui.close": "Close",
  "ui.back": "Back",
  "nav.breadcrumbs": "Breadcrumbs",

  "hero.eyebrow": "Booking platform · 2026 · Norway",
  "hero.words":
    "Venues|Function rooms|Meeting rooms|Sports halls|Cultural centres|Wedding venues|Party venues|Community halls",
  "hero.headlineTail": "you need,",
  "hero.headlineEm": "and the platform behind them",
  "hero.lede":
    "Find and book venues with real prices and real availability, and pay securely. If you rent space out, you run everything from the calendar to settlement in one platform.",
  "hero.bullet1": "Real prices and live availability",
  "hero.bullet2": "Pay securely by card, mobile payment or invoice",
  "hero.bullet3": "Built for Norwegian requirements — national ID, GDPR and accessibility",

  "how.label": "HOW IT WORKS",
  "how.intro": "From request to settlement: one continuous process.",
  "how.headline": "Booking in",
  "how.headlineEm": "a few steps.",
  "how.step1.title": "Request",
  "how.step1.body":
    "A resident, club, association or business sends a request through Digilist. Availability is shown live, and requests that fit the rules are booked immediately.",
  "how.step2.title": "Approval",
  "how.step2.body":
    "Requests outside the rules go to an administrator. Approval can be delegated to operational roles, and automatic rules cover recurring patterns such as seasonal allocation.",
  "how.step3.title": "Confirmation",
  "how.step3.body":
    "Automatic confirmation with the details, and payment by card or mobile payment. Operational roles — caretaker, cleaning, security — are notified automatically.",
  "how.step4.title": "Follow-up",
  "how.step4.body":
    "Invoices and vouchers to the common accounting systems, or by the European e-invoicing standard. Reporting, KPIs and financial reconciliation in one platform.",

  "cta.label": "BOOK A DEMO",

  "market.label": "FIND AND BOOK",
  "market.intro":
    "Venues, accommodation, events, equipment and services in one place. Real prices, real availability, and secure payment.",
  "market.headline": "Everything you can find and",
  "market.headlineEm": "book",
  "market.tile.venues": "Venues",
  "market.tile.venues.tag": "Function · meeting · culture",
  "market.tile.stays": "Accommodation",
  "market.tile.stays.tag": "Cabin · apartment · holiday home",
  "market.tile.sport": "Sport and activity",
  "market.tile.sport.tag": "Sports hall · padel · swimming",
  "market.tile.events": "Events",
  "market.tile.events.tag": "Concert · theatre · sport",
  "market.tile.equipment": "Equipment",
  "market.tile.equipment.tag": "Party · tools · outdoor",
  "market.tile.services": "Services",
  "market.tile.services.tag": "Catering · DJ · decor",

  "faq.label": "FREQUENTLY ASKED",
  "faq.intro":
    "What people most often ask about Digilist: booking, payment, pricing and compliance. Cannot find your answer?",
  "faq.headline": "Frequently asked",
  "faq.headlineEm": "questions",
  "faq.seeAll": "See all questions",

  "sync.label": "CHANNELS · TWO-WAY SYNC",
  "sync.headline": "One calendar.",
  "sync.headlineEm": "every channel",
  "sync.lede":
    "Listed on Airbnb, Booking.com or another channel? Connect them to Digilist once, and your calendar and availability stay in sync automatically. No duplicate work, no double bookings, always current everywhere.",
  "sync.benefit1": "Sync calendar, prices and availability automatically",
  "sync.benefit2": "Add new listings without doing the work twice",
  "sync.benefit3": "Always current — never a double booking",
  "sync.benefit4": "One admin for every channel",
  "sync.cta": "See how sync works",

  "agents.label": "BUILT-IN INTELLIGENCE",
  "agents.intro":
    "Underneath, a fleet of AI agents approves, answers, explains and notifies — so the administration does not have to.",
  "agents.headline": "Agents and",
  "agents.headlineEm": "automation",
  "agents.a1.title": "Approval and compliance",
  "agents.a1.body":
    "Every listing is checked against GDPR, security and accessibility standards — text and images both — before it is published. Clean content is approved; the rest is stopped with specific guidance.",
  "agents.a2.title": "Answering enquiries",
  "agents.a2.body":
    "Enquiries get a warm, accurate first reply straight away, reading the purpose, the date and the numbers. Complaints, pricing and legal questions always go to a person.",
  "agents.a3.title": "Seasonal allocation",
  "agents.a3.body":
    "Reviews and explains how recurring slots are allocated to local clubs. It catches the clubs that miss out, judges whether the outcome is defensible, and gives each one a reason. Never “the system decided”.",
  "agents.a4.title": "The day ahead",
  "agents.a4.body":
    "Caretakers, cleaning, security and fire safety get a calm, personal view of the day, with the times in order and what needs following up. Never an empty message.",
  "agents.a5.title": "Market insight",
  "agents.a5.body":
    "Reads supply and demand across the marketplace and finds the gaps — where the venues people are actually searching for do not exist — as a short, ranked list of opportunities.",
  "agents.a6.title": "Draft a listing from a link",
  "agents.a6.body":
    "Already listed elsewhere, or have the details in a document? Paste the link or upload the file, and the agent reads it and produces a finished draft listing for you to polish.",

  "b2b.label": "FOR OPERATORS AND PUBLIC BODIES",
  "b2b.intro":
    "Digilist runs private rental and public-sector booking in one system: individual bookings, recurring seasonal slots for local clubs, shared use across departments, and resident access through national digital identity.",
  "b2b.headline": "From one venue to",
  "b2b.headlineEm": "an entire authority",
  "b2b.b1.title": "Everything in one place",
  "b2b.b1.body":
    "Orders, calendar, prices, terms and administration in one platform. No more spreadsheets, email threads and double bookings.",
  "b2b.b2.title": "Simple to use",
  "b2b.b2.body":
    "Residents and tenants find a free slot, send a request and pay without being trained. Built to WCAG accessibility standards.",
  "b2b.b3.title": "Efficient to run",
  "b2b.b3.body":
    "Automated rules, approvals and oversight cut manual work. Operational roles are notified automatically when a booking lands.",
  "b2b.b4.title": "Scales with you",
  "b2b.b4.body":
    "From a single function room to an authority with twelve facilities: seasonal allocation, clubs and associations, grants and invoicing.",

  "demo.heading": "Book a demo",
  "demo.lede":
    "We do not run a canned demo. Tell us briefly what you run, and we will show the parts that actually apply to you.",
  "demo.badge1": "No commitment",
  "demo.badge2": "Quick reply",
  "demo.badge3": "Walked through with you",
  "demo.formHeading": "Send us a few details.",
  "demo.name": "Name",
  "demo.namePlaceholder": "Jane Doe",
  "demo.email": "Email",
  "demo.emailPlaceholder": "jane@example.com",
  "demo.org": "Organisation",
  "demo.orgPlaceholder": "Your organisation",
  "demo.phone": "Phone (optional)",
  "demo.role": "What kind of organisation?",
  "demo.message": "What matters most to you? (optional)",
  "demo.messagePlaceholder":
    "Seasonal allocation, sign-in, invoicing, number of venues, procurement requirements …",
  "demo.submit": "Send request",
  "demo.submitting": "Sending …",
  "demo.thanks": "Thank you — we will be in touch.",
  "demo.sentTo": "The request has been sent to",
  "demo.replyTime": "replies within 24 hours on weekdays, usually sooner.",
  "demo.error":
    "We could not send the request. Try again, or email us directly at kontakt@digilist.no.",
  "demo.role.kommune": "Public body",
  "demo.role.selskapslokale": "Function room / operator",
  "demo.role.idrett": "Sports facility",
  "demo.role.kulturhus": "Cultural venue / stage",
  "demo.role.kontor": "Office / coworking",
  "demo.role.annet": "Something else",
  "demo.get1": "A 30–45 minute demo, shaped around what you run",
  "demo.get2": "A walk through booking, payment, seasonal allocation and invoicing",
  "demo.get3": "Questions and answers — we do not run a canned demo",
  "demo.get4": "A note with concrete next steps if you are considering a pilot",
  "demo.need1": "What kind of organisation, and roughly how many bookings",
  "demo.need2": "Any procurement or internal compliance requirements",
  "demo.need3": "Which roles should see the demo (administration, operations, finance)",

  "hero.trust1": "Book in 90 seconds",
  "hero.trust1.sub": "Simple and fast",
  "hero.trust2": "Accessible by design",
  "hero.trust2.sub": "WCAG 2.1 AA",
  "hero.trust3": "Secure sign-in and payment",
  "hero.trust3.sub": "National ID supported",
  "hero.trust4": "Live availability",
  "hero.trust4.sub": "Real prices",

  "lane.renter.eyebrow": "If you are looking to rent",
  "lane.renter.heading": "Find and book a venue near you",
  "lane.renter.body":
    "Community halls, cultural venues and function rooms in one place, with real prices, real availability and secure payment. Book directly — no ringing round, no waiting for a reply.",
  "lane.owner.eyebrow": "If you rent space out",
  "lane.owner.heading": "The platform that runs the letting",
  "lane.owner.body":
    "Booking, seasonal allocation and resident enquiries in one platform, with compliance built in. One system replacing spreadsheets, email threads and ad-hoc payment links, so you keep the whole picture. Residents and clubs book themselves, around the clock, with no phone queue and no double bookings.",
  "lane.chooser": "Pick the one that fits — we will show you the way.",
  "agents.cta": "See how the agents work →",
  "pilot.label": "FREE PILOT FOR NORWEGIAN PUBLIC BODIES",
  "pilot.cta": "See the solution for public bodies",
  "stories.intro":
    "Everyday stories from Norwegian operators. Bookings, automation and accounting, joined up.",
  "stories.footnote":
    "More references available on request. Contact sales for customer and performance references.",
  "stories.caption": "Two of several — references on request",
  "blogPreview.intro":
    "Three articles on public-sector booking, seasonal allocation and compliance, written for the people who administer them.",

  "chat.assistant": "The Digilist assistant",
  "chat.show": "Show the Digilist assistant",
  "chat.close": "Close the Digilist assistant",
  "chat.closeConversation": "Close conversation",
  "chat.suggestions": "Suggested next questions",
  "chat.suggestionsLabel": "Digilist assistant, suggestions",
  "chat.closeSuggestions": "Close suggestions",
  "chat.yourMessage": "Your message",
  "chat.needHelp": "What do you need help with?",
  "chat.details": "Details about your needs, timeline or questions…",
  "chat.org": "Organisation",
  "chat.orgExample": "e.g. Riverside Function Rooms",

  "pricing.title": "Pricing: a subscription, with no transaction fee | Digilist",
  "pricing.description":
    "Digilist takes no share of your booking revenue. Subscription tiers set by venues and needs, tailored pricing for small and private operators, and 6 months free for the first 100 customers.",
  "pricing.label": "PRICING",
  "pricing.h1": "We take no share of what",
  "pricing.h1em": "you earn",
  "pricing.lede":
    "Digilist is a subscription, not a commission. You pay to use the platform and the administration panel — no transaction fee, no per-booking cost, and no hidden charges. What you charge for a rental is yours.",
  "pricing.cta": "Get a quote for your setup",
  "pricing.faqCta": "Read the full FAQ",
  "pricing.visual": "SUBSCRIPTION · NO COMMISSION",
  "pricing.howHeading": "How the price works.",
  "pricing.whyHeading": "Why there is no price list",
  "pricing.whyBody":
    "The gap between a community hall with one room and a county authority with twenty-two schools is wide enough that any single figure is either too high for one or meaningless to the other. We publish everything that decides the price instead, and give a concrete quote after a short conversation. Tell us how many venues, what they are used for, and roughly how many rentals a year — and you have a number.",
  "pricing.faqHeading": "Common questions about price.",
  "pricing.offerHeading": "The first 100 customers get 6 months free.",
  "pricing.offerBody":
    "No lock-in during the trial. A booking system is impossible to judge properly from a demo — you find out in the busy month, when three groups want the same room.",
  "pricing.start": "Get started",

  "faqPage.title": "FAQ · Digilist | Common questions about booking and compliance",
  "faqPage.description":
    "Answers to the most common questions about Digilist: what it costs, what we never charge for, where data is stored, and who the platform is for.",
  "faqPage.h1": "Frequently asked",
  "faqPage.h1em": "questions",
  "faqPage.lede":
    "What Digilist costs, what we never charge for, where your data lives, and who the platform is built for.",
  "faqPage.categories": "Categories",
  "faqPage.stillQuestions": "STILL HAVE QUESTIONS?",
  "faqPage.talkHeading": "Talk to us directly.",
  "faqPage.talkBody":
    "We answer email quickly, or book a free 30-minute demo where we show the platform for your situation.",
  "faqPage.talkCta": "Chat with us",

  "footer.funksjonalitet": "Features",
  "footer.brukerhistorier": "Customer stories",
  "footer.kontakt": "Contact",
  "footer.lokaler": "Venues",
  "footer.lokaler_til_leie": "Venues to rent",
  "footer.overnatting": "Accommodation",
  "footer.arrangementer": "Events",
  "footer.utstyr": "Equipment",
  "footer.tjenester": "Services",
  "footer.booking_av_lokaler_og_m_terom": "Venue and meeting-room booking",
  "footer.bookingsystem_for_utleie": "Booking system for operators",
  "footer.bookingsystem_for_kommuner": "Booking system for public bodies",
  "footer.billettsystem": "Ticketing",
  "footer.teknologi": "Technology",
  "footer.sikkerhet": "Security",
  "footer.priser": "Pricing",
  "footer.om_oss": "About us",
  "footer.blogg": "Blog",
  "footer.faq": "FAQ",
  "footer.transparens": "Transparency",
  "footer.utleiemarkedet_2026": "The rental market 2026",
  "footer.personvern": "Privacy",
  "footer.salgsvilk_r": "Terms",
  "footer.cookies": "Cookies",
  "footer.tilgjengelighet": "Accessibility",

  "search.placeholder": "Search Digilist…",
  "search.label": "Search Digilist",
  "search.shortcuts": "Shortcuts",
  "search.popular": "Popular searches",
  "search.blog": "Blog",

  "stories.a.headline": "From spreadsheet to automated calendar.",
  "stories.a.dek": "A private function room outside Oslo, let out for parties, weddings and anniversaries.",
  "stories.a.body": "The owner wanted to stop tracking bookings in a spreadsheet. With Digilist, guests get a link where they see the free weekends themselves, pay the deposit and sign the rental agreement digitally.",
  "stories.a.quote": "We have eliminated double bookings and got automatic invoicing. Every booking goes from enquiry to paid in under five minutes.",
  "stories.a.byline": "Owner",
  "stories.b.headline": "One platform for halls, meeting rooms and canteens.",
  "stories.b.dek": "A public culture department with twelve facilities, around 340 clubs and associations, and 1,200 bookings a month.",
  "footer.tagline": "One platform for Norwegian venues. Find and book as an individual; run and manage as an operator or public body.",
  "footer.colophon": "SET DIGITALLY · OSLO · IN NEWSREADER AND INTER",
  "demo.chatLine": "and get an answer in chat in under a minute during office hours.",
  "home.title": "Digilist · Booking software for venues that are rented out",
  "home.description": "Booking platform for function rooms, sports halls, meeting rooms and cultural venues. Live availability, secure payment, seasonal allocation. A subscription with no transaction fee.",
  "stories.a.customer": "CUSTOMER",
  "stories.b.body": "The culture officer handles seasonal allocation to clubs and associations, private bookings, and shared use between canteens and meeting rooms. Operational roles — caretakers, cleaning, security — are notified automatically when a booking is confirmed. Grants to clubs are distributed through the seasonal-allocation module.",
  "stories.b.quote": "We have brought twelve facilities, hundreds of associations and public invoicing into one platform, and residents book with national digital identity.",
  "stories.b.byline": "CULTURE OFFICER · A NORWEGIAN MUNICIPALITY",
  "stories.b.stat1": "FACILITIES RUNNING",
  "stories.b.stat2": "ACTIVE CLUBS",
  "stories.b.stat3": "BOOKINGS / MONTH",
  "stories.reference": "REQUEST A REFERENCE",
  "market.find": "FIND",
  "footer.ctaHeading": "Ready to see Digilist in practice?",
  "footer.productOf": "A product of",
  "blog.back": "Back to the blog",
  "blog.readArticle": "Read article",
  "demo.whatYouGet": "WHAT YOU GET",
  "demo.whatWeNeed": "WHAT WE NEED FROM YOU",
  "demo.informalChat": "Prefer an informal chat first?",
  "demo.weFollow": "We follow",
  "demo.privacyPolicy": "our privacy statement",
  "stories.a.body2": "The owner wanted to stop tracking bookings in a spreadsheet. With Digilist, guests get a link where they see the free weekends themselves, pay the deposit and sign the rental agreement digitally.",
  "blog.crumbVenues": "Venue and meeting-room booking",
  "blog.crumbHalls": "Sports halls and gyms",
  "blog.crumbMunicipal": "Booking system for public bodies",
  "blog.crumbMeeting": "Meeting rooms",
  "blog.crumbFunction": "Function rooms",
  "blog.crumbCulture": "Cultural venues and canteens",
  "useCase.crumbRoot": "Use cases",
  "useCase.breadcrumbs": "Breadcrumbs",
  "useCase.challenges": "What the challenges are today",
  "useCase.whatWeDo": "What Digilist does about it",
  "useCase.whoUses": "Who uses this",
  "about.title": "About Digilist: a Norwegian booking platform | Digilist",
  "about.description": "Digilist is built by Xala Technologies AS, a Norwegian technology company. We build one platform for private rental and public-sector booking, with compliance and data stored in Norway and the EU.",
  "demo.choose": "Select …",
  "homePricing.whyNoList": "We publish no price list: the gap between a community hall with one room and a county authority with twenty-two schools makes any single number wrong for almost everyone. We publish everything that decides it instead.",
  "homePricing.rule": "PRICING · LAUNCH OFFER",
  "homePricing.h2": "A subscription,",
  "homePricing.h2em": "not a commission",
  "homePricing.lede": "We take no share of what you charge. You pay to use Digilist and its administration panel — not per booking, not a percentage of the rent, and no hidden fees. Going from twenty rentals a year to sixty does not make Digilist cost more.",
  "homePricing.privateLabel": "PRIVATE OPERATORS",
  "homePricing.privateTitle": "One venue or fifty",
  "homePricing.privateBody": "Function rooms, community halls, farms, clubs and associations. The tier follows how many venues you have and how many people use the system — not how much you earn. Going from one venue to five changes the subscription; more bookings in the same venue does not. Smaller and private operators get their own tailored pricing.",
  "homePricing.publicLabel": "PUBLIC BODIES",
  "homePricing.publicTitle": "Facilities, not bookings",
  "homePricing.publicBody": "The price depends on the number of facilities, how many people use the system, and the integrations with your finance and case systems. Seasonal allocation, national identity sign-in, e-invoicing and SSA-L 2026 are part of the platform, not extras. No share of what residents, clubs and associations pay.",
  "homePricing.offerEyebrow": "LAUNCH OFFER",
  "homePricing.offerTitle": "Six months free for the first 100 customers",
  "homePricing.offerBody": "We help with setup and publishing during the trial, and you get your own administrative access to carry on from there. No lock-in along the way — afterwards you choose a tier based on what you need.",
  "homePricing.ctaPrices": "See what decides the price",
  "homePricing.ctaDemo": "Request a quote",
  "homePricing.noFee": "No transaction fee",
  "homePricing.noHidden": "No hidden charges",
  "homePricing.included": "Integrations included",
  "a11y.homeLink": "Digilist, go to the home page",
  "a11y.heroVideo": "Digilist in practice — from search to booking",
  "chat.searchPlaceholder": "Search or ask about Digilist …",
  "demo.orgOrCouncil": "Organisation or public body",
  "useCase.howItWorks": "HOW IT WORKS",
  "useCase.seeHow": "SEE HOW IT WORKS",
  "status.card.report": "Per-surface scores for SEO, accessibility, security and links — the same data our own team sees.",
  "status.card.meeting": "30–45 min, under NDA: a summary of the most recent penetration test, vulnerability status and contingency plan.",
  "status.card.securityTxt": "Found a vulnerability? We accept responsible disclosure at sikkerhet@digilist.no, acknowledged within 24 hours.",
  "tr.card.meeting": "30–45 minutes, under NDA: a summary of the most recent penetration test, vulnerability status, RPO/RTO and contingency plan.",
  "tr.card.securityTxt": "Found a vulnerability? We accept responsible disclosure at sikkerhet@digilist.no, acknowledged within 24 hours.",
  "tr.areasIntro": "The report covers five areas.",
  "tr.areaSeo": "SEO",
  "tr.areaSeoBody": "measures how visible the platform is in search: titles, metadata, canonical tags and structured data.",
  "tr.areaA11y": "Accessibility",
  "tr.areaA11yBody": "checks conformance with WCAG: heading order, alt text, landmarks and keyboard navigation for screen readers.",
  "tr.areaSec": "Security",
  "tr.areaSecBody": "assesses HTTP security headers, TLS certificates, and that no sensitive files are exposed.",
  "tr.areaUptime": "Uptime",
  "tr.areaUptimeBody": "tracks availability and response time per service, with alerting when something deviates.",
  "tr.areaLinks": "Links",
  "tr.areaLinksBody": "verifies that no outbound link is broken. Every surface in the platform — the marketing site, the booking app, the dashboard, the documentation and the API — is scanned independently, and the figures below are taken directly from the most recent run, with no manual editing or selection.",
  "tr.measuredUptime": "MEASURED UPTIME (30 DAYS)",
  "tr.avgScore": "Average score",
  "tr.warnings": "Warnings",
  "tr.methodRule": "METHOD",
  "tr.apiError": "The API responded with",
  "tr.apiErrorTail": ". Try reloading the page",
  "tr.unknownType": "an unknown type",
  "tr.fw.iso27001": "Annex A: organisational, people, physical and technological controls.",
  "tr.fw.soc2": "Common Criteria: control environment, risk, access and system operations.",
  "tr.fw.gdpr": "Core articles: privacy, lawful basis, erasure and breach handling.",
  "tr.val.ssl": "Certificate, cipher suites, protocol strength. Target A or A+.",
  "tr.val.headers": "HSTS, CSP, X-Frame-Options, Referrer-Policy. A letter grade.",
  "tr.val.observatory": "Overall security posture against modern web standards.",
  "tr.val.pagespeed": "Core Web Vitals: LCP, CLS, INP. Mobile and desktop.",
  "tr.comp.iso27001": "Information security management",
  "tr.comp.iso27701": "Privacy information management",
  "tr.comp.gdpr": "Data stored in the EU/EEA",
  "tr.label.security": "Security",
  "tr.col.uptime": "Uptime",
  "tr.col.security": "Security",
  "tr.col.a11y": "Accessibility",
  "tr.col.seo": "SEO",
  "tr.col.links": "Links",
  "tr.m.uptime": "Uptime & SSL.",
  "tr.m.uptimeBody": "HTTP status, response time and certificate expiry via",
  "tr.m.seo": "SEO.",
  "tr.m.seoBody": "Titles, descriptions, canonical tags, OG/Twitter, JSON-LD, alt text, duplicate metadata, broken internal links.",
  "tr.m.a11y": "Accessibility.",
  "tr.m.a11yBody": "The lang attribute, alt text, label-for, heading order, ARIA landmarks, button and link names (a cheerio baseline; axe-core to come).",
  "tr.m.sec": "Security.",
  "tr.m.secBody": "HSTS, CSP, X-Frame-Options, X-Content-Type-Options, Referrer-Policy, Permissions-Policy, probes for exposed sensitive files, mixed content, source maps.",
  "tr.m.links": "Links.",
  "tr.m.linksBody": "Outbound links checked with HEAD, falling back to GET on 405, de-duplicated per URL.",
  "tr.metaTitle": "Transparency · quality report for Digilist",
  "tr.metaDescription": "A live quality report: SEO, accessibility, security, uptime and links, scanned automatically across the Digilist platform.",
  "tr.h1": "Transparency.",
  "tr.lede1a": "A public-sector CIO should know what kind of platform they are choosing. This page shows",
  "tr.ledeEm": "Digilist's own",
  "tr.lede1b": "quality: SEO, accessibility, security, uptime and links, scanned and updated automatically.",
  "tr.lede2": "Scans run at least every 15 minutes for uptime, and daily across the whole platform. What we show here is what our own team sees.",
  "tr.loading": "Fetching live data…",
  "tr.errorPrefix": "Sorry — back shortly.",
  "tr.surfacesActive": "Surfaces active",
  "tr.criticalFindings": "Critical findings",
  "tr.noBlocking": "Nothing blocking",
  "tr.underRemediation": "Being fixed",
  "tr.recommendedImprovement": "Recommended improvement",
  "tr.complianceNote": "The figures show degree of implementation: the share of applicable controls with a documented state of «Implemented» (full credit) or «Partial» (half). Detail on each individual control is available on request to public-sector customers under NDA.",
  "tr.noSurfaces": "No active production surfaces in the most recent scan.",
  "tr.whatWeMeasure": "What we measure",
  "tr.scoreReading": "How to read the scores",
  "tr.band95": "excellent",
  "tr.band85": "good",
  "tr.band70": "acceptable",
  "tr.validatorRule": "INDEPENDENT ASSESSMENT",
  "tr.validatorH2": "Verify us with independent third parties",
  "tr.validatorLede": "We run our own automated scans, shown above — but you should not take our word for it. Check digilist.no yourself with these independent security and quality services. They give a live verdict.",
  "tr.liveReport": "See the live report",
  "tr.liveNote": "A live lookup. Click a box to run a third-party scan in real time.",
  "tr.complianceRule": "COMPLIANCE",
  "tr.nextRule": "WHAT NEXT",
  "tr.nextH2": "Want to see more?",
  "tr.nextLede": "We are happy to share a summary of the most recent penetration test and our vulnerability status under NDA. Ask for a meeting and we will show the reports alongside the platform.",
  "tr.readAudit": "Read about security auditing",
  "tr.score.excellent": "Excellent",
  "tr.score.good": "Good",
  "tr.score.acceptable": "Acceptable",
  "tr.score.needsWork": "Needs improvement",
  "tr.score.critical": "Critical",
  "tr.score.noData": "No data",
  "tr.label.uptime": "SSL & response time",
  "tr.label.a11y": "Accessibility",
  "status.metaTitle": "Service status · Digilist",
  "status.metaDescription": "Live status for the Digilist platform: uptime, SLA, security and availability across digilist.no, app.digilist.no, dashboard.digilist.no and the documentation.",
  "status.h1": "Status.",
  "status.lede1": "Live status for the Digilist platform. Every surface is scanned automatically. We measure what",
  "status.ledeEm": "you",
  "status.lede2": "experience, not just a server pulse. When something breaks, you see it here first.",
  "status.slaNote": "The SLA figures below are commitments. Falling short of a target triggers an incident report, published in the log at the bottom of this page.",
  "status.lastUpdated": "Last updated",
  "status.scanNote": "scans run automatically · this page shows the most recent scan available",
  "status.loading": "Fetching live data…",
  "status.unavailable": "The status measurements are not loading right now. The scans are still running in the background.",
  "status.slaRule": "SLA COMMITMENTS",
  "status.slaH2": "Committed uptime vs. actual.",
  "status.slaLede": "We commit to specific uptime figures per surface type. The figure",
  "status.slaNoData": "No data",
  "status.slaMet": "SLA met",
  "status.slaBreach": "Below SLA",
  "status.surfacesRule": "SURFACES",
  "status.surfacesLede": "Per-surface status (operational, degraded or down) based on the most recent",
  "status.incidentRule": "INCIDENT LOG",
  "status.noIncidents": "No incidents recorded in the last 90 days.",
  "status.validatorRule": "INDEPENDENT ASSESSMENT",
  "status.validatorH2": "Verify us with independent third parties",
  "status.validatorLede": "The figures above come from our own scans. Check digilist.no",
  "status.liveReport": "See the live report",
  "status.nextRule": "WHAT NEXT",
  "status.nextH2": "Need more detail?",
  "status.nextLede": "A full transparency report, a security meeting under NDA, and responsible",
  "status.eco.operational": "All systems operational",
  "status.eco.degraded": "Reduced performance on some surfaces",
  "status.eco.outage": "An incident is in progress on at least one surface",
  "status.dot.operational": "Operational",
  "status.dot.degraded": "Degraded",
  "status.dot.down": "Down",
  "status.type.marketing": "Marketing",
  "status.type.app": "App",
  "status.type.dashboard": "Dashboard",
  "status.type.docs": "Documentation",
  "status.type.api": "API",
  "status.type.status": "Status",
  "status.sla.marketing": "Public pages: marketing, blog, documentation",
  "status.sla.docs": "Documentation",
  "status.sla.status": "This status page",
  "status.sla.app": "Signed-in application surfaces",
  "status.sla.dashboard": "Tenant administration",
  "status.sla.api": "Public API endpoints",
  "tools.title": "Free tools for renting a venue: price and size | Digilist",
  "tools.description": "Free tools for anyone renting a venue: a rental price calculator and a capacity calculator. Estimate price and floor area for a wedding, party, meeting or conference — no sign-in.",
  "tools.keywords": "venue rental tools, rental price calculator, capacity calculator, event planning, venue budget",
  "tools.crumb": "Tools",
  "tools.h1": "Free tools for renting a venue",
  "tools.lede": "Simple, honest tools for planning an event — estimate the price and the floor area before you start looking for a venue. No sign-in, no commitment.",
  "tools.open": "Open the tool",
  "tools.priceTitle": "Price calculator",
  "tools.priceDesc": "What does it cost to rent a venue? An honest, indicative price range adjusted for venue type, city, day of the week and season.",
  "tools.capTitle": "Capacity calculator",
  "tools.capDesc": "How big a venue do you need? Work out the recommended floor area from your guest count and layout, and see which venue types fit.",
  "calc.type.selskapslokale": "Function room / party venue",
  "calc.type.grendehus": "Community hall",
  "calc.type.moterom": "Meeting room",
  "calc.type.konferanselokale": "Conference venue",
  "calc.type.kulturhus": "Cultural venue / large hall",
  "calc.type.idrettshall": "Sports hall",
  "calc.city.oslo": "Oslo",
  "calc.city.bergen": "Bergen",
  "calc.city.trondheim": "Trondheim",
  "calc.city.stavanger": "Stavanger",
  "calc.city.kristiansand": "Kristiansand",
  "calc.city.tromso": "Tromsø",
  "calc.city.drammen": "Drammen",
  "calc.city.baerum": "Bærum",
  "calc.city.annet": "Elsewhere / a smaller place",
  "calc.unit.dag": "day",
  "calc.unit.arrangement": "event",
  "calc.unit.time": "hour",
  "calc.factor.weekend": "Weekend",
  "calc.factor.weekday": "Weekday",
  "calc.factor.highSeason": "High season, May–Sep",
  "calc.factor.lowSeason": "Low season",
  "price.title": "Venue price calculator: what does it cost to rent? | Digilist",
  "price.description": "A free rental price calculator: an honest, indicative price range for a function room, meeting room, conference venue, cultural venue or sports hall — adjusted for city, season and day of the week. Not a quote, but a good guide for a budget.",
  "price.keywords": "what does it cost to rent a venue, venue rental price, function room price, venue price calculator, hall hire cost",
  "price.crumb": "Price calculator",
  "price.howH2": "How we work out the estimate",
  "price.howP1a": "The estimate starts from typical price ranges for each venue type in the Norwegian rental market, then adjusts them by a few clearly stated factors. We always give a ",
  "price.howP1strong": "range",
  "price.howP1b": " rather than an exact price, because the real price depends on the particular venue.",
  "price.b1strong": "Venue type and size",
  "price.b1": " matter most. A community hall costs a fraction of a central function room.",
  "price.b2strong": "City and area:",
  "price.b2": " central Oslo and the larger cities sit higher; smaller places are cheaper.",
  "price.b3strong": "Day of the week:",
  "price.b3": " Saturdays are the most sought-after and the most expensive; weekdays are cheaper and more available.",
  "price.b4strong": "Season:",
  "price.b4": " May to September is high season for weddings and parties.",
  "price.howP2a": "Remember that ",
  "price.howP2strong": "additional services",
  "price.howP2b": " — cleaning, staffing, AV equipment, catering and a deposit — usually come on top of the base rent. On Digilist these appear as separate lines, so you see the final total before you confirm.",
  "price.h1": "What does it cost to rent a venue?",
  "price.ledeA": "An honest, indicative price range for renting a venue in Norway — adjusted for venue type, guest count, city, day of the week and season. This is ",
  "price.ledeStrong": "an estimate, not a quote",
  "price.ledeB": ": the actual price is set by the operator and is shown on each individual venue.",
  "price.venueType": "Venue type",
  "price.city": "City / area",
  "price.weekend": "Weekend (Sat/Sun)",
  "price.highSeason": "High season (May–September)",
  "price.estimated": "Estimated rental price",
  "price.per": "per",
  "price.adjustedFor": "Adjusted for:",
  "price.disclaimer": "An indicative range, not a quote. The actual price varies with the venue and any additional services.",
  "price.findAvailable": "Find available",
  "price.realPrices": "See real prices and available dates for",
  "price.empty": "Choose a venue type for an estimate.",
  "price.guestsWord": "guests",
  "cap.ledeA": "Work out the recommended floor area from your guest count and layout, and see which venue types fit. These are ",
  "cap.ledeStrong": "standard planning figures",
  "cap.ledeB": " — a good guide, not a rule.",
  "cap.howP1b2": " — that is, whether guests are sitting or standing. A seated dinner with round tables needs the most space; a standing reception the least.",
  "cap.rowDinner": "Seated dinner (round tables):",
  "cap.rowMingle": "Standing reception:",
  "cap.rowClass": "Classroom / training:",
  "cap.rowTheatre": "Theatre style (rows of chairs):",
  "cap.perGuest": "per guest.",
  "cap.perPersonShort": "per person.",
  "cap.howP2a": "Add space for a ",
  "cap.howP2strong": "dance floor, stage, buffet, bar, cloakroom and escape routes",
  "cap.howP2b": " — typically 15–25% extra. If children will be running about, or your programme is varied, choose a venue towards the upper end of the range.",
  "cap.title": "Venue size calculator: how big a room do you need? | Digilist",
  "cap.description": "A free capacity calculator: work out how large a venue (m²) you need from your guest count and layout — seated dinner, standing reception, classroom or theatre style. With standard planning figures and suggested venue types.",
  "cap.keywords": "how big a venue, venue capacity, m2 per guest, how many guests, capacity calculator, guest count venue",
  "cap.crumb": "Capacity calculator",
  "cap.badge": "Free tool",
  "cap.h1": "How big a venue do you need?",
  "cap.lede": "Work out the recommended floor area from your guest count and layout, and see which venue types fit. These are standard planning figures, not binding.",
  "cap.guests": "Number of guests",
  "cap.occasion": "Type of occasion",
  "cap.layout": "Layout",
  "cap.perPerson": "m² per person",
  "cap.recommended": "Anbefalt areal",
  "cap.for": "for",
  "cap.guestsWord": "guests",
  "cap.basis": "Add 15–25% for a dance floor, stage, buffet and cloakroom. These are standard planning figures — always check the venue's stated capacity.",
  "cap.basedOn": "Based on",
  "cap.typesFor": "Venue types that fit",
  "cap.findVenues": "Find available venues",
  "cap.empty": "Enter a guest count for an estimate.",
  "cap.howH2": "How to work out capacity",
  "cap.faqH2": "Frequently asked questions",
  "cap.explore": "Explore further",
  "cap.venuesToRent": "Venues to rent",
  "cap.howP1a": "Floor area is driven first of all by the",
  "cap.howP1strong": "layout",
  "cap.howP1b": " — that is, whether guests are sitting or standing. A seated dinner with round tables needs the most space; a standing reception the least.",
  "cap.byline": "The Digilist editors",
  "cap.bylineRole": "Booking system for venue operators",
  "calc.oppsett.middag": "Seated dinner (round tables)",
  "calc.oppsett.mingling": "Standing reception",
  "calc.oppsett.klasserom": "Classroom / training (tables and chairs)",
  "calc.oppsett.kino": "Theatre style (rows of chairs)",
  "calc.arr.bryllup": "Wedding",
  "calc.arr.konfirmasjon": "Confirmation",
  "calc.arr.firmafest": "Company party / Christmas dinner",
  "calc.arr.mote": "Meeting",
  "calc.arr.konferanse": "Conference",
  "calc.arr.mingling": "Reception",
  "pilot.delivers.0": "A real-time availability calendar",
  "pilot.delivers.1": "Straightforward booking and requests",
  "pilot.delivers.2": "Seasonal allocation for clubs and associations",
  "pilot.delivers.3": "An overview of venues and sports facilities",
  "pilot.delivers.4": "A digital case-handling flow",
  "pilot.delivers.5": "Administrative approval of requests",
  "pilot.delivers.6": "Invoicing basis and payment overview",
  "pilot.delivers.7": "A mobile-friendly, accessible interface",
  "pilot.delivers.8": "Simple administration and content updates",
  "pilot.delivers.9": "Better visibility for municipal facilities and activities",
  "pilot.needs.0": "The venues or facilities the municipality administers",
  "pilot.needs.1": "Short descriptions",
  "pilot.needs.2": "Images or links, where available",
  "pilot.needs.3": "Contact details",
  "pilot.needs.4": "Any information about booking or seasonal allocation",
  "pilot.rule": "PILOT FOR NORWEGIAN MUNICIPALITIES",
  "pilot.h2": "An invitation to",
  "pilot.h2em": "Norwegian municipalities",
  "pilot.p1": "Digilist is a modern, accessible platform for managing municipal venues, sports facilities, meeting rooms and events — and for making them visible to the people who want to use them.",
  "pilot.p2": "We are inviting municipalities to join a pilot, where we help make municipal venues and activities more available, simpler to administer, and easier for residents, clubs, organisations and event organisers to find.",
  "pilot.p3em": "The aim is not to replace existing systems",
  "pilot.p3tail": "or ways of working, but to explore how Digilist can work as a modern complement for residents and for the administration.",
  "pilot.p4": "We help with setup and publishing at no cost during the pilot. The municipality gets its own administrative access to carry on from there.",
  "pilot.requestCta": "Request a pilot",
  "pilot.role": "Xala Technologies AS",
  "pilot.date": "Oslo · 2026",
  "pilot.offerLabel": "WHAT WE PROVIDE",
  "pilot.deliverEm": "provides",
  "pilot.inputLabel": "INPUT FROM THE MUNICIPALITY",
  "pilot.needH3": "What we need",
  "pilot.needH3em": "from the municipality",
  "pilot.footnote": "The pilot is free of charge. The municipality takes on no commitment to continue or to procure.",
  "tech.title": "Technology and security: the stack behind Digilist",
  "tech.description": "The technology behind Digilist: React 19, the Convex reactive runtime, PostgreSQL 16 in Norway and the EU, ISO 27001/27701, GDPR, WCAG 2.1 AA, and the Norwegian identity and e-invoicing integrations.",
  "tech.rule": "PLATFORM · SECURITY · COMPLIANCE",
  "tech.h1": "The technology",
  "tech.h1em": "behind Digilist",
  "tech.lede": "A reactive runtime, data stored in Norway and the EU, and compliance built in from the start: ISO 27001/27701, GDPR and accessibility. Here is the stack, the architecture and the integrations that run the platform.",
  "tech.faqRule": "FREQUENTLY ASKED QUESTIONS",
  "tech.faqH2": "Technology and",
  "tech.faqH2em": "compliance",
  "tech.faqLede": "Stack, data storage, certifications and uptime: the answers technical buyers and case officers ask for.",
  "tech.seeAll": "See all questions",
  "tech.ctaHeading": "Want to see under the hood?",
  "tech.ctaBody": "Book a demo and we will walk through the architecture, where data lives, the compliance documentation, and the integrations that matter for your setup.",
  "bookDemo.title": "Book a Digilist demo · Booking for venues and councils",
  "bookDemo.description": "Request a free 30–45 minute demo of Digilist. We will show how the platform handles your case: a public body, a function room, a sports facility or a cultural venue.",
  "bookDemo.back": "Back to the home page",
  "bookDemo.rule": "IX. CONTACT",
  "bookDemo.crumb": "Book a demo",
  "about.label": "ABOUT DIGILIST",
  "about.h1": "One platform for everything",
  "about.h1em": "that is rented out",
  "about.lede": "Digilist is built by Xala Technologies AS, a Norwegian technology company. We build software for the public sector and for business, starting from compliance, accessibility and data stored in Norway and the EU.",
  "about.techCta": "Technology & security",
  "about.ctaHeading": "Talk to the people who build it.",
  "about.ctaBody": "Book a demo or get in touch, and we will show you how Digilist fits your organisation.",
  "chat.closeShort": "Close",
  "pilot.body": "We help you set up and publish at no cost during the pilot, and you get your own administrative access for running it afterwards. The aim is to supplement your existing processes, not replace them.",
  "footer.ctaBody": "Book a personal demo, or ask questions directly in chat. We answer in under a minute during office hours.",
  "blogPreview.seeAll": "See all articles",
  "interest.finn": "Find and book a venue",
  "interest.kalender": "Booking & calendar",
  "interest.betaling": "Payment & settlement",
  "interest.kanaler": "Channels & sync",
  "interest.ai": "AI agents",
  "interest.kommune": "Booking for public bodies",
  "interest.heading": "What are you most interested in?",
  "chat.s1": "Find a function room",
  "chat.s2": "What does it cost to rent a venue?",
  "chat.s3": "Booking system for public bodies",
  "chat.s4": "Seasonal allocation",
  "chat.s5": "Book a demo",
  "footer.i_navigasjon": "I · NAVIGATION",
  "footer.ii_markedsplass": "II · MARKETPLACE",
  "footer.iii_l_sninger": "III · SOLUTIONS",
  "footer.iv_selskap": "IV · COMPANY",
  "footer.v_lokaler_til_leie": "V · VENUES TO RENT",
};

const DICT: Record<Locale, Copy> = { nb, en };

/**
 * Look up a string.
 *
 * Falls back to Norwegian, then to the key itself. Never throws and never
 * renders empty: a missing translation should read as untranslated text, which
 * someone notices, rather than as a blank button, which looks like a broken
 * page and gets misdiagnosed.
 */
export function t(locale: Locale, key: string): string {
  return DICT[locale]?.[key] ?? nb[key] ?? key;
}

/** Every key, for the test that keeps the two languages in step. */
export function copyKeys(locale: Locale): string[] {
  return Object.keys(DICT[locale] ?? {});
}
